In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.arange.html
import numpy as np

##The Basics

In [104]:
a=np.array([1,2,3], dtype="int32")
a

array([1, 2, 3], dtype=int32)

In [105]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
#Get Dimension
a.ndim

1

In [6]:
#get shape
b.shape

(2, 3)

In [15]:
#get type
a.dtype

dtype('int32')

In [11]:
#get size
a.itemsize
b.itemsize

8

In [13]:
#Get total size
a.nbytes

24

#Accessing/Changing specific elements, rows, column, etc

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
#Get a specific element[r, c]
a[1,5]

13

In [21]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [40]:
#Getting a little more fancy[startindex:endindex:stepsize]
print(a)
#startindex starting index starts at 0 which is equivalent to 1
#endindex ending index ends at 7
#stepsize
  #*set to 1 is integer (display all in range)
  #*set to 2 is real (display both start & ends only )
  #*set to 3 is optional
a[0,1:-1:2] # end(which is 7) -1 = 6

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

In [41]:
#replace value 1d sample
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [46]:
#replace value 2d sample
a[:,2] =[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [49]:
#replace value 3d sample
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
#Get specific element(work outside in)
b[0,1,1]

4

In [52]:
#replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initiazing Different Types of Arrays

In [55]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
#All 1s matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [59]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [62]:
#Any other number(full like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [64]:
#Random decimal numbers
np.random.rand(4,2,3)

array([[[0.301157  , 0.53168213, 0.70562228],
        [0.27897773, 0.53200956, 0.33293448]],

       [[0.30382227, 0.20717406, 0.60885611],
        [0.45960276, 0.88472338, 0.843065  ]],

       [[0.041535  , 0.5178789 , 0.86876278],
        [0.85866876, 0.12151126, 0.85616138]],

       [[0.4715531 , 0.32638934, 0.17888499],
        [0.56631067, 0.38523243, 0.05293369]]])

In [66]:
np.random.random_sample(a.shape)

array([[0.52100498, 0.53831595, 0.69654623, 0.01486177, 0.41099247,
        0.35743036, 0.16655731],
       [0.99942622, 0.22504711, 0.09023088, 0.29529136, 0.70482347,
        0.67991291, 0.91270256]])

In [74]:
#random Integer values
np.random.randint(4,7,size=(3,3))

array([[6, 6, 4],
       [5, 6, 4],
       [5, 5, 6]])

In [76]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
#repeat an array
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [106]:
#Excercise
#Fit the small array to the big array
#big array
output = np.ones((7,7))

#small array
z = np.zeros((5,5))

#solution
z[2,2] = 3
#print(z)
output[1:6,1:6] = z
print(output)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 3. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [88]:
#copying array
a=np.array([1,2,3])
b=a.copy
b

array([1, 2, 3])

In [89]:
#reused copyied array
b[0] = 100
print(b)

[100   2   3]


#Mathematics

In [110]:
i = np.array([1,2,3,4])
print(i)

[1 2 3 4]


In [111]:
#division
i/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [115]:
#Multiplication
i*2

array([2, 4, 6, 8])

In [116]:
#Addition
i+1

array([2, 3, 4, 5])

In [117]:
#Subtraction
i-1

array([0, 1, 2, 3])

In [119]:
#Raise to 3
i ** 3

array([ 1,  8, 27, 64])

In [120]:
b=np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [121]:
a = np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [122]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [124]:
#find the determinat
c = np.identity(3)
np.linalg.det(c)


1.0

#Statistics

In [126]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
np.min(stats, axis=1)

array([1, 4])

In [130]:
np.max(stats, axis=1)

array([3, 6])

In [132]:
np.sum(stats)

21

#Reorganizing Array

In [136]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [150]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [157]:
#Vertically Stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [158]:
#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])